apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: schoolapp-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore

  target:
    name: {{ .Values.externalSecrets.targetSecret }}
    creationPolicy: Owner      # ESO owns this K8s Secret — deletes it when ExternalSecret is deleted

  data:
    - secretKey: connectionstring
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: connectionstring
