apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets        # ESO's own IRSA-annotated service account
            namespace: external-secrets   # ESO lives in this namespace
